# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: mongodb://database:27017/tutorial
    ports:
      - '4000:4000'
    depends_on:
      - database

#  start the mongodb service as container
# version: '3.8'
# services:
  database:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGODB_DATABASE="tutorial"
    restart: always
    ports:
      - '27017:27017'
